---
services:
  frontend:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: 80
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/app/
      - /mnt/e/test_footage/:/var/app/public/videos
      - /var/app/node_modules
  backend:
    build:
      context: ./backend
    environment:
      PORT: 80
    ports:
      - "3000:80"
    volumes:
      - ./backend/src:/var/app/src
      - /mnt/e/test_footage/:/var/app/public/videos
      - ./videos/:/var/app/videos
  flower:
    image: 'vid-editor-backend:latest'
    environment:
      redisHost: redis
    volumes:
      - ./backend/src:/var/app/src
      - /mnt/e/test_footage/:/var/app/public/videos
      - ./videos/:/var/app/videos
    command: nodemon -L ./src/flower.js
  trimmer:
    image: 'vid-editor-backend:latest'
    environment:
      redisHost: redis
    volumes:
      - ./backend/src:/var/app/src
      - /mnt/e/test_footage/:/var/app/public/videos
      - ./videos/:/var/app/videos
    command: nodemon -L ./src/trimmer.js
  joiner:
    image: 'vid-editor-backend:latest'
    environment:
      redisHost: redis
    volumes:
      - ./backend/src:/var/app/src
      - /mnt/e/test_footage/:/var/app/public/videos
      - ./videos/:/var/app/videos
    command: nodemon -L ./src/joiner.js
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongo:8.0.9"
    ports:
      - "27017:27017"
