---
services:
  frontend:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: 80
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/app/
      - /mnt/e/test_footage/:/var/app/public/videos
      - /var/app/node_modules
  backend:
    build:
      context: ./backend
    environment:
      PORT: 80
    ports:
      - "3000:80"
    volumes:
      - ./backend/src:/var/app/src
      - /mnt/e/test_footage/:/var/app/public/videos
      - ./videos/:/var/app/videos
  consumer:
    build:
      context: ./backend
    environment:
      PORT: 80
    ports:
      - "3001:80"
    volumes:
      - ./backend/src:/var/app/src
    command: node ./src/consumer.js
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
